server:
  port: 8092 #服务注册中心端口号

spring:
  application:
    name: service-consumer

eureka:
  instance:
    hostname: eureka-consumer.com #服务注册中心IP地址
    prefer-ip-address: false
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry:  true
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://eureka-master.com:8090/eureka/,http://eureka-Branch.com:8094/eureka/

#ribbon:
#  eager-load:
#    clients:
#    enabled:
#  secure-ports:
#  restclient:
#    enabled: false
#  eureka:
#    enabled: false
#  http:
#    client:
#      enabled: false
#  okhttp:
#    enabled: false


feign:
  #  okhttp:
  #    enabled: false
  #  client:
  #    config:
  #    default-config:
  #    default-to-properties:
  ## 请求和响应进行压缩，GZIP压缩，以减少通信过程中的性能损耗
  #  compression:
  #    request:
  #      enabled: true #请求压缩
  #      mime-types: text/html,application/xml,application/json #设置压缩的数据类型
  #      min-request-size: 2048 #设置触发压缩的大小下限
  #    response:
  #      enabled: true  #响应压缩
  #
  #  httpclient:
  #    connection-timeout:
  #    connection-timer-repeat:
  #    disable-ssl-validation: false
  #    enabled: false
  #    follow-redirects: false
  #    max-connections:
  #    max-connections-per-route:
  #    time-to-live:
  #    time-to-live-unit: days
  hystrix:
    enabled: true #添加feign对Hystrix的支持



# 配置hystrix
hystrix:
  threadpool:
    default:
      coreSize: 10  #线程池核心线程数
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #超时时间
      circuitBreaker:
        requestVolumeThreshold: 3  #当在配置时间窗口内达到此数量后，进行短路。默认20个
        sleepWindowInMilliseconds: 5  #短路多久以后开始尝试是否恢复，默认5s
        errorThresholdPercentage: 50%  #出错百分比阈值，当达到此阈值后，开始短路。默认50%
  stream:
    enabled: true


#turbine配置
turbine:
  app-config:
  aggregator:
    cluster-config:
  cluster-name-expression:
  app-config-list:
  combine-host-port: true
