server:
  port: 8014 #服务注册中心端口号

spring:
  application:
    name: zuul


eureka:
  instance:
    hostname: eureka-zuul.com #服务注册中心IP地址
    prefer-ip-address: false
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry:  true
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://eureka-master.com:8090/eureka/,http://eureka-Branch.com:8094/eureka/
zuul:
  routes:
      server-provider:
        path: /xl/**
       # url: http://eureka-providera.com:8091/
        serviceId : service-provider
  retryable: true #是否开启重试功能
ribbon:
  maxAutoRetries: 2
  MaxAutoRetriesNextServer : 0


#如果忽略以上配置文件则默认访问路径  默认访问规则 http://ZUUL_HOST:ZUUL_PORT/微服务在Eureka上的serviceId/**会被转发到serviceId对应的微服务。
#http://eureka-zuul。com:8014/service-provider/getUser?id=1




