server:
  port: 8094 #服务注册中心端口号

eureka:
  instance:
    hostname: eureka-Branch.com #服务注册中心IP地址
    prefer-ip-address: false
  client:
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://eureka-master.com:8090/eureka/
  server:
    enableSelfPreservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 10000

spring:
  application:
    name: service
